config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :phone_numbers

  accepts_nested_attributes_for :phone_numbers

  validates :name, presence: true
  validates :email, uniqueness: {scope: :name}, allow_blank: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  def avatar
    clean_email = email.strip.downcase
    Digest::MD5.hexdigest(clean_email)
  end
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :contact

  validates_format_of :phone, with: /(\d{3}-)?\d{3}-\d{4}/

  enum type: [:home, :work, :mobile, :fax]

  scope :primary, -> { where(primary: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  helper_method :column_sort, :direction_sort

  def index
    if params[:sort] || params[:direction] || params[:page]
      session[:column_sort] = params[:sort] if params[:sort]
      session[:direction_sort] = params[:direction] if params[:direction]
      session[:page] = params[:page] if params[:page]
    end

    @contacts = Contact.
      order(column_sort + " " + direction_sort).
      paginate(page: session[:page] || params[:page], per_page: 10)
  end

  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  end

  def create
    @contact = Contact.new(contact_params)

    @contact.save

    if @contact.errors.any?
      render :new
    else
      redirect_to contacts_path
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update_attributes(contact_params)
      redirect_to contacts_path
    else
      render :index
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    name = @contact.name

    if @contact.destroy
      redirect_to contacts_path
    else
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :birthday, :notes)
  end

  def column_sort
    return session[:column_sort] if session[:column_sort]
    Contact.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def direction_sort
    return session[:direction_sort] if session[:direction_sort]
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == column_sort && direction_sort == "asc" ? "desc" : "asc"
    link_to title, {sort: column, direction: direction}
  end
end

app/views/contacts/_contact.html.erb
<div class="detail-container">
  <span class="glyphicon glyphicon-remove"></span>
  <div class="input-group">
    <div class="input-group-addon">Name</div>
    <div class="data-field"><%= contact.name %></div>
  </div>

  <div class="input-group">
    <div class="input-group-addon">@</div>
    <div class="data-field"><%= contact.email %></div>
  </div>

  <div class="input-group">
    <div class="input-group-addon"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></div>
    <div class="data-field"><%= contact.phone %></div>
  </div>

  <div class="input-group">
    <div class="input-group-addon">Birthday</div>
    <div class="data-field"><%= contact.birthday || "No birthday entered" %></div>
  </div>

  <div class="input-group">
    <div class="input-group-addon">Notes</div>
    <div class="data-field"><%= contact.notes %></div>
  </div>

  <div class="input-group">
    <%= link_to "Edit", edit_contact_path(contact), remote: true, class: 'btn btn-primary' %>
  </div>
</div>
 

app/views/contacts/_edit_contact.html.erb
<%= form_for @contact do |f| %>

  <div class="detail-container">
    <span class="glyphicon glyphicon-remove"></span>

    <%= render partial: 'form', locals: {f: f} %>

  </div>

<% end %>

app/views/contacts/_form.html.erb
<div class="input-group">
  <span class="input-group-addon"><%= f.label :name  %></span>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="input-group">
  <span class="input-group-addon">@</span>
  <%= f.text_field :email, :class => "form-control" %>
</div>

<div class="input-group">
  <span class="input-group-addon"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></span>
  <div class="phone-container">
    <%= f.fields_for :phone_numbers_attributes do |pnf| %>
      <span><%= pnf.text_field :phone_number, class: "form-control", placeholder: "###-###-####" %></span>
      <span>Type: <%= pnf.select :type, options_for_select(PhoneNumber.types) %></span>
      <span>Primary? <%= pnf.check_box :primary %></span>
    <% end %>
  </div>
</div>

<div class="input-group">
  <span class="input-group-addon"><%= f.label :birthday %></span>
  <%= f.text_field :birthday, class: "form-control datepicker" %>
</div>

<div class="input-group">
  <span class="input-group-addon"><%= f.label :notes %></span>
  <%= f.text_area :notes, class: "form-control" %>
</div>

<div class="input-group">
  <%= f.submit :class => 'btn btn-primary' %>
</div>

app/views/contacts/edit.js.erb
$(".detail-view").html("<%= escape_javascript(render partial: 'edit_contact', locals: { contact: @contact}) %>");

$(".glyphicon-remove").on("click", function(event) {
  event.preventDefault();
  $(".detail-view").toggle();
});

$(".datepicker").datepicker();

app/views/contacts/index.html.erb
<% if @contact && @contact.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    Contact could not be deleted due to the following <%= "error".pluralize(@contact.errors.count) %>:
    <ul>
      <% @contact.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<table class="table">
  <tr>
    <th> </th>
    <th><span><%= sortable "name", "Name" %></span></th>
    <th><span><%= sortable "email", "E-mail" %></span></th>
    <th><span><%= sortable "phone", "Phone" %></span></th>
    <th> </th>
  </tr>
 
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= image_tag "https://www.gravatar.com/avatar/#{contact.avatar}" %></td>
      <td><%= link_to contact.name, contact_path(contact), remote: true %></td>
      <td><%= mail_to contact.email, contact.email, subject: "Hello #{contact.name}" %></td>
      <td><%= contact.phone %></td>
      <td><%= link_to "Delete", contact_path(contact), class: 'btn btn-danger', data: { method: :delete, confirm: "Are you sure you want to delete #{contact.name}?" } %></td>
    </tr>
  <% end %>

  <tr><td colspan="4" class="page-footer"><%= will_paginate @contacts %></td></tr>
</table>

<div class="detail-view">

</div>

app/views/contacts/new.html.erb
<%= form_for :contact, url: contacts_path do |f| %>

  <% if @contact && @contact.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    Contact could not be saved due to the following <%= "error".pluralize(@contact.errors.count) %>:
    <ul>
      <% @contact.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
 
  <%= render partial: 'form', locals: {f: f} %>


<% end %>

app/views/contacts/show.js.erb
$(".detail-view").html("<%= escape_javascript(render partial: 'contact', locals: { contact: @contact}) %>");

$(".glyphicon-remove").on("click", function(event) {
  event.preventDefault();
  $(".detail-view").toggle();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlexCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
			<ul class="nav navbar-nav">
			<li role="presentation" <%= 'class=active' if current_page?(root_path) || current_page?(controller: 'contacts', action: 'index') %>><%= link_to 'Home', contacts_path %></li>
			<li role="presentation" <%= 'class=active' if current_page?(controller: 'contacts', action: 'new') %>><%= link_to 'Add Contact', new_contact_path %></li>
			</ul>
	    </div>
	  </div>
	</nav>

    <%= yield %>

  <div class="app-footer">
    &copy; Copyright <%= Date.today.year %> ContactStartupCorp, Inc.<br />
    UltraContactManager&reg; is a registered trademark of ContactStartupCorp, Inc.
  </div>
  </body>
</html>